# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI For Sample Python application

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  # Organization Secrets
  AWS_ACCESS_KEY_ID: ${{ secrets.PERSONAL_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PERSONAL_AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: 086230238707
  ECR_REPOSITORY: 086230238707.dkr.ecr.ap-northeast-2.amazonaws.com
  AWS_REGION: ap-northeast-2 # AWS EKS & ECR이 위치한 AWS Region
  STAGE: demod_apnortheast2
  CLUSTER_NAME: demodapne2-abcd
  NAMESPACE: default
  APP_NAME: sample-app
  
jobs:  
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Src
        uses: actions/checkout@v3

      - name: fetch src
        run: git fetch --prune --unshallow
  
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest

      - name: Get Tag with py
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ env.AWS_ACCOUNT_ID }}
  
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
            chmod +x "${GITHUB_WORKSPACE}/.github/buildscript.sh"
            ./.github/buildscript.sh ${{ env.ECR_REPOSITORY }} ${{ steps.vars.outputs.sha_short }}
        shell: bash
        
      - name: Checkout k8s-env
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: namejsjeongkr/devops_k8s_env
          ref: main
  
      - name: Update Image tag
        run: |
          sed -i '/^/s/tag:.*/tag: ${{ steps.vars.outputs.sha_short }}/' ./${STAGE}/${CLUSTER_NAME}/${NAMESPACE}/${APP_NAME}/bluegreen/image.yaml
          sed -i '/^/s/tag:.*/tag: ${{ steps.vars.outputs.sha_short }}/' ./${STAGE}/${CLUSTER_NAME}/${NAMESPACE}/${APP_NAME}/canary/image.yaml
          ls
        shell: bash
  
      - name: GIT commit and push docs
        env:
          CI_COMMIT_MESSAGE: Update Tag - ${{ steps.vars.outputs.tag }}
          CI_COMMIT_AUTHOR: namejsjeongkr
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "namejsjeongkr@lguplus.co.kr"
          git status
          git add -A
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push origin main
